import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const { version } = JSON.parse(readFileSync(`${root}/package.json`, 'utf8'));

// Escribimos ambas versiones directamente como texto JS para evitar imports de JSON en runtime
writeFileSync(
  `${root}/src/version.ts`,
  `// Auto-generated by scripts/gen-version.mjs — do not edit.\nexport const version = ${JSON.stringify(version)};\nexport const coreVersion = "7.0.15";\n`,
);